name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
    # Exclude direct pushes to master and production branches
    paths-ignore:
      - 'production'
  pull_request:
    types: [closed]
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run coverage

  deploy_to_github_pages:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy to GitHub Pages
        run: |
          npm install
          npm run build
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout gh-pages
          git pull origin gh-pages --rebase
          cp -r dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages